[package]
name = "ci"
edition = "2021"
description = "Tool that enables running CI checks locally."
publish = false
license = "MIT OR Apache-2.0"

[dependencies]
argh = "0.1"
serde_json = "1.0.116"
serde = { version = "1.0.200", features = ["derive"] }

[lints]
workspace = true

[package.metadata.docs.rs]
rustdoc-args = ["-Zunstable-options", "--cfg", "docsrs"]
all-features = true
